<?php

$sql = array(
    "setutf" => "SET NAMES 'utf8'",
    "get_promos" => "SELECT * FROM `promos` WHERE promo_enabled = 1",
    "get_promos_all" => "SELECT * FROM `promos`",
    "get_promos_bysite" => "SELECT * FROM `promos` WHERE promo_enabled = 1 AND promo_site LIKE '%[0]%'",
    "get_promo_by_id" => "SELECT * FROM `promos` WHERE promo_id = [0]",
    "insert_promo" => "INSERT INTO `promos` VALUES (NULL , {0}, {1}, 0, 'rolunk')",
    "delete_promo" => "DELETE FROM `promos` WHERE `promo_id` = [0]",
    "delete_offer_request1" => "DELETE FROM `offer_requests` WHERE `offer_id` = [0]",
    "delete_offer_request2" => "DELETE FROM `offer_trucks` WHERE `offer_id` = [0]",
    "delete_offer_request3" => "DELETE FROM `offer_images` WHERE `offer_id` = [0];",
    "delete_company" => "DELETE FROM `companies` WHERE `company_id` = [0]",
    "getuser" => "SELECT * FROM `users` WHERE `users_id`=[0]",
    "set_promo_enabled" => "UPDATE `promos` SET `promo_enabled` = 1 WHERE `promo_id` IN ([0])",
    "set_promo_disabled" => "UPDATE `promos` SET `promo_enabled` = 0 WHERE `promo_id` NOT IN ([0])",
    "truck_details" => "SELECT
        truck_id,
        `truck_saxon-id`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
        truck_model,
        (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
        `truck_max-load`,
        `truck_max-height`,
        (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
        `truck_full-height`,
        `truck_cabin-height`,
        `truck_length`,
        `truck_width`,
        `truck_lifting-column-height`,
        (SELECT value FROM truck_type_[0] WHERE truck_type_[0].ID = trucks.truck_type) AS truck_type,
        truck_cost,
        truck_reseller_price,
        truck_date,
        truck_reserved,
        `truck_reserve-start`,
        `truck_reserve-end`,
        `truck_special-offer-active`,
        `truck_special-offer-start`,
        `truck_special-offer-end`,
        `truck_special-offer-price`,
        `truck_default-image`,
        CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location,
        truck_desc,
        `truck_powered-wheel`,
        `truck_steered-wheel`,
        `truck_engine`,
        `truck_drivetrain`,
        `truck_hours-used`,
        `truck_year`,
        `truck_serial`,
        `truck_weight`,
        `truck_extras`,
        `truck_internal-desc`,
        `truck_warranty`,
        `truck_expected-arrival`,
        `truck_ispart`,
        `truck_short-comment`,
        `truck_forks`,
         truck_public,
        (SELECT COUNT(*) FROM truck_images WHERE truck_images.`image_truck-id` = {1}) AS truck_imagecount
      FROM trucks WHERE trucks.truck_id = {1}",
    "truck_lesserdetails" => "SELECT
        `truck_saxon-id`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
        truck_model,
        (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
        (SELECT value FROM truck_type_[0] WHERE truck_type_[0].ID = trucks.truck_type) AS truck_type,
        `truck_default-image`,
        `truck_special-offer-active`,
        `truck_special-offer-start`,
        `truck_special-offer-end`,
        `truck_special-offer-price`,
        (SELECT COUNT(*) FROM truck_images WHERE truck_images.`image_truck-id` = {1}) AS truck_imagecount,
        truck_cost
      FROM trucks WHERE trucks.truck_id = {1}",
    "truck_updated" => "UPDATE trucks SET `truck_date` = NOW() WHERE `truck_id` = {0}",
    "truck_getimage" => "SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = {0} AND truck_images.image_id = {1}",
    "truck_getimageByUniqueId" => "SELECT * FROM truck_images WHERE truck_images.`image_unique-id` = {0};",
    "truck_getdefaultimage" => "SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = {0} AND truck_images.image_id = (SELECT `truck_default-image` FROM trucks WHERE `truck_id` = {0})",
    "truck_addimage" => "INSERT INTO truck_images (`image_truck-id`, `image_id`, `image_filename`) VALUES ({0}, {1}, {2})",
    "truck_deleteimage" => "DELETE FROM truck_images WHERE `image_truck-id` = {0} AND `image_id` = {1}",
    "truck_updateimages" => "UPDATE truck_images SET `image_id` = `image_id` - 1 WHERE `image_truck-id` = {0} AND `image_id` > {1}",
    "truck_setdefaultimage" => "UPDATE trucks SET `truck_default-image` = {0} WHERE `truck_id` = {1} LIMIT 1",
    "truck_setimage_illustration" => "UPDATE truck_images SET `image_illustration` = {0} WHERE `image_unique-id` = {1} LIMIT 1",
    "truck_setimage_notworking" => "UPDATE truck_images SET `image_notworking` = {0} WHERE `image_unique-id` = {1} LIMIT 1",
    "truck_getimages" => "SELECT * FROM truck_images WHERE truck_images.`image_truck-id` = {0} ORDER BY `image_id`",
    "truck_getimagecount" => "SELECT COUNT(*) FROM truck_images WHERE truck_images.`image_truck-id` = {0}",
    "truck_get_pdf" => "SELECT offer_pdf FROM offer_requests WHERE `offer_id` = {0}",
    "truck_get_pdf_truck" => "SELECT * FROM trucks WHERE `truck_id` = {0}",
    
    "get_inserttext_full" => "SELECT * FROM inserttext WHERE `insert_id`>0",
    "get_inserttext_id" => "SELECT * FROM inserttext WHERE `insert_id` = {0}",
    "delete_inserttext" => "DELETE FROM inserttext WHERE `insert_id` = {0}",
    "get_text_inserttext" => "SELECT * FROM inserttext WHERE `insert_name` = {0}",
    "update_inserttext" => "UPDATE inserttext SET `insert_name` = {1}, `insert_value` = {2} WHERE `insert_id` = {0}",
    "insert_inserttext" => "INSERT INTO inserttext (`insert_name`,`insert_value`) VALUES ({0},{1})",
    
    
    "update_method" => "UPDATE paymode SET `Name` = {1} WHERE `ID` = {0}",
    "get_method_id" => "SELECT * FROM paymode WHERE `ID` = {0}",
    "get_text_method" => "SELECT * FROM paymode WHERE `Name` = {0}",
    "insert_method" => "INSERT INTO paymode (`Name`,`Days`,`State`) VALUES ({0},0,'A')",
    "get_method_min_id" => "SELECT ID FROM paymode WHERE `ID` >0 ORDER BY ID ASC LIMIT 1",
    
    "update_delivery" => "UPDATE deliverymethods SET `Name` = {1} WHERE `ID` = {0}",
    "get_delivery_id" => "SELECT * FROM deliverymethods WHERE `ID` = {0}",
    "get_text_delivery" => "SELECT * FROM deliverymethods WHERE `Name` = {0}",
    "insert_delivery" => "INSERT INTO deliverymethods (`Name`,`State`) VALUES ({0},'A')",
    "get_delivery_min_id" => "SELECT ID FROM deliverymethods WHERE `ID` >0 ORDER BY ID ASC LIMIT 1",
    
    "get_offer_useremail" => "SELECT `users`.`users_email` FROM `offer_requests`, `users` WHERE `users`.`users_id`=`offer_requests`.`offer_user-id` AND `offer_requests`.`offer_id`={0}",
    
    "truck_get-highest-image-id" => "SELECT MAX(image_id) AS `lastimage` FROM truck_images WHERE `image_truck-id` = {0}",
    "truck_getspecialoffer" => "SELECT `truck_special-offer-active`, `truck_special-offer-start`, `truck_special-offer-end`, `truck_special-offer-price`, `truck_cost`, `truck_saxon-id` FROM trucks WHERE truck_id = {0}",
    "truck_get-reserve" => "SELECT `truck_reserved`, `truck_reserve-start`, `truck_reserve-end`, `truck_saxon-id` FROM trucks WHERE truck_id = {0}",
    "truck_setspecialoffer" => "UPDATE trucks SET `truck_special-offer-active` = {1}, `truck_special-offer-start` = {2}, `truck_special-offer-end` = {3}, `truck_special-offer-price` = {4} WHERE truck_id = {0} LIMIT 1",
    "truck_set-reserve" => "UPDATE trucks SET `truck_reserved` = {1}, `truck_reserve-start` = {2}, `truck_reserve-end` = {3} WHERE truck_id = {0} LIMIT 1",
    "truck_search_saxonid" => "SELECT `truck_saxon-id` FROM `trucks` WHERE `truck_saxon-id` LIKE '%[0]%'",
    "trucks_filteredlist" => "SELECT
        truck_id,
        `truck_saxon-id`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
        truck_model,
        (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
        `truck_max-height`,
        `truck_max-load`,
        (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
        (SELECT value FROM truck_type_[0] WHERE truck_type_[0].ID = trucks.truck_type) AS truck_type,
        truck_cost,
        `truck_special-offer-active`,
        `truck_special-offer-start`,
        `truck_special-offer-end`,
        `truck_special-offer-price`,
				`truck_reseller_price`,
				`truck_date`,
				`truck_depot`,
        `truck_state`,
				`truck_public`,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = trucks.truck_id AND truck_images.image_id = trucks.`truck_default-image` LIMIT 1) AS `truck_default-image`,
				(SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = trucks.truck_id AND truck_images.image_id = trucks.`truck_default-image` LIMIT 1) AS `truck_image`,
				(SELECT COUNT(*) FROM truck_images WHERE truck_images.`image_truck-id` = trucks.`truck_id`) AS truck_imagecount
      FROM trucks [1] ORDER BY trucks.`truck_saxon-id` [2]",
    "trucks_filteredlist_count" => "SELECT COUNT(*) FROM trucks [0]",
    "aktualis-filter_saxon-id" => "SELECT DISTINCT `truck_saxon-id` AS value FROM trucks WHERE `truck_state` = 'A' AND `truck_ispart` = {0} ORDER BY `truck_saxon-id`",
    "aktualis-filter_make" => "SELECT * FROM truck_make_" . $lang . " ORDER BY value",
    "aktualis-filter_functions" => "SELECT * FROM truck_functions_" . $lang . " WHERE `ispart` = {1} ORDER BY value",
    "aktualis-filter_functions-admin" => "SELECT * FROM truck_functions_" . $lang . " ORDER BY value",
    "aktualis-filter_akcios_termekek" => "SELECT truck_id as ID, `truck_saxon-id` as value FROM `trucks` WHERE `truck_special-offer-end`>NOW() AND `truck_special-offer-price`>0 AND `truck_ispart` = {1} ORDER BY value",
    "aktualis-filter_model" => "SELECT DISTINCT truck_model AS value FROM trucks WHERE `truck_state` = 'A' AND `truck_ispart` = {0} ORDER BY truck_model",
    "aktualis-filter_max-height" => "SELECT DISTINCT `truck_max-height` AS value FROM trucks ORDER BY `truck_max-height`",
    "aktualis-filter_fuel" => "SELECT * FROM truck_fuel_[0] ORDER BY value",
    "aktualis-filter_status" => "SELECT * FROM truck_status_[0] ORDER BY value",
    "aktualis-filter_type" => "SELECT * FROM truck_type_[0] WHERE `ispart` = {1} ORDER BY value",
    "aktualis-filter_alltype" => "SELECT * FROM truck_type_[0] ORDER BY value",
    "aktualis-filter_location" => "SELECT * FROM truck_location WHERE `depot` != -1 AND NOT((`depot` BETWEEN 4 AND 7) AND `subdepot` = 1) AND `depot` != 7 ORDER BY value",
    "login" => "SELECT * FROM users WHERE users_login = '[0]' AND users_pass = '[1]'",
    "usernameexists" => "SELECT * FROM users WHERE users_login = '[0]'",
    "register" => "",
    "update_offer_request_options" => "UPDATE `offer_requests` SET `offer_payment` = {1}, `offer_reserve` = {2}, `offer_euro` = {3}, `offer_lifetime` = {4}, `offer_lang` = {5}, `offer_signature` = {6}, `offer_deliverymethod` = {7}, `offer_pdf` = {8} WHERE `offer_id` = {0}",
    //"add_offer_request" => "INSERT INTO `offer_requests` VALUES(0,[0],[1],{2},'', 0, 0, NOW(), NOW(), '0000-00-00 00:00:00',0,1, 0, 0, 'hun')",
    "add_offer_request" => "INSERT INTO `offer_requests` ( `offer_id` , `offer_user-id` , `offer_clerk-id` , `offer_trucks` , `offer_message` , `offer_type` , `offer_status` , `offer_date-added` , `offer_date-last-edited` , `offer_date-closed` , `offer_changed` , `offer_payment` , `offer_reserve` , `offer_euro` , `offer_lang` , `offer_comment`,`offer_text` )
                             VALUES (
                             NULL , [0], [1], {2}, '', 0, 0, NOW(), NOW(), '0000-00-00 00:00:00', 0, 1, 50, 0, 'hun', '', {3})",
    "get_user_company" => "SELECT * FROM `companies` WHERE `company_id` = {0}",
    "get_offer_request:all" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      `offer_clerk-id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_clerk-id`) AS offer_clerkname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` ORDER BY `offer_id` DESC",
    "get_offer_request:search" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      `offer_clerk-id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_clerk-id`) AS offer_clerkname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` WHERE [0] ORDER BY `offer_id` DESC",
    "get_offer_request:clerk" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      `offer_clerk-id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_clerk-id`) AS offer_clerkname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` WHERE `offer_clerk-id`={0}",
    "get_offer_request:wip" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      `offer_clerk-id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_clerk-id`) AS offer_clerkname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` WHERE `offer_clerk-id`='-1' OR `offer_status`='1' ORDER BY `offer_id` DESC",
    "get_offer_request:customer" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` WHERE `offer_user-id`={0}",
    "get_offer_request:status" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      `offer_clerk-id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_clerk-id`) AS offer_clerkname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` WHERE `offer_status`={0} ORDER BY `offer_id` DESC",
    "offer_request:take" => "UPDATE `offer_requests` SET `offer_clerk-id` = {1}, `offer_status` = '1' WHERE `offer_id` = {0}",
    "get_offer_request:user" => "SELECT
      `offer_id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_user-id`) AS users_realname,
      `offer_clerk-id`,
      (SELECT `users_realname` FROM users WHERE users.users_id = offer_requests.`offer_clerk-id`) AS offer_clerkname,
      (SELECT `company_name` FROM `companies` WHERE `company_id` = (SELECT `users_company` FROM `users` WHERE `users`.`users_id` = `offer_requests`.`offer_user-id`)) AS offer_company_name,
      offer_trucks,
      offer_status,
      offer_message,
      offer_type,
      `offer_date-added`,
      `offer_date-last-edited`,
      `offer_date-closed`,
      offer_changed,
      offer_payment,
	    offer_reserve,
	    offer_euro,
	    offer_lang,
      offer_comment,
      offer_text,
      offer_signature
      FROM `offer_requests` WHERE `offer_user-id`={0}",
    "get_offer_request:id" => "SELECT offer_requests.*, deliverymethods.Name as deliverymethod FROM `offer_requests` 
        LEFT JOIN deliverymethods ON deliverymethods.ID=offer_requests.offer_deliverymethod WHERE `offer_id` = {0}",
    "get_offer_trucks" => "SELECT `offer_trucks` FROM `offer_requests` WHERE `offer_id` = [0]",
    "get_trucks_in_offer_request" => "SELECT
        `offer_truck_id`,
        `offer_truck_saxon-id`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = offer_trucks.offer_truck_make) AS offer_truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = offer_trucks.offer_truck_function) AS offer_truck_function,
        offer_truck_model,
        (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = offer_trucks.offer_truck_fuel) AS offer_truck_fuel,
        `offer_truck_max-load`,
        `offer_truck_max-height`,
        (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = offer_trucks.offer_truck_status) AS offer_truck_status,
        (SELECT value FROM truck_type_[0] WHERE truck_type_[0].ID = offer_trucks.offer_truck_type) AS offer_truck_type,
        offer_truck_cost,
        offer_truck_date,
        offer_truck_reserved,
        `offer_truck_default-image`,
        CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = offer_trucks.offer_truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = offer_trucks.offer_truck_depot AND truck_location.subdepot = offer_trucks.`offer_truck_sub-depot`)) AS offer_truck_location,
        offer_truck_desc,
        `offer_truck_powered-wheel`,
        `offer_truck_steered-wheel`,
        `offer_truck_engine`,
        `offer_truck_drivetrain`,
        `offer_truck_hours-used`,
        `offer_truck_year`,
        `offer_truck_serial`,
        `offer_truck_weight`,
        `offer_truck_extras`,
        `offer_truck_internal-desc`,
        `offer_truck_warranty`,
        `offer_truck_expected-arrival`,
        `offer_truck_ocomment`,
        `offer_truck_vtsz`,
        `offer_truck_fake-image`
      FROM offer_trucks WHERE offer_trucks.offer_truck_id IN ([1]) AND offer_trucks.offer_id=[2]",
    "copy_truck_to_offer" => "INSERT INTO `offer_trucks` (
                              `offer_trucks_id` ,
                              `offer_id` ,
                              `offer_truck_id` ,
                              `offer_truck_saxon-id` ,
                              `offer_truck_make` ,
                              `offer_truck_function` ,
                              `offer_truck_model` ,
                              `offer_truck_fuel` ,
                              `offer_truck_max-load` ,
                              `offer_truck_max-height` ,
                              `offer_truck_status` ,
                              `offer_truck_type` ,
                              `offer_truck_cost` ,
                              `offer_truck_rent` ,
                              `offer_truck_date` ,
                              `offer_truck_reserved` ,
                              `offer_truck_default-image` ,
                              `offer_truck_powered-wheel` ,
                              `offer_truck_steered-wheel` ,
                              `offer_truck_engine` ,
                              `offer_truck_drivetrain` ,
                              `offer_truck_hours-used` ,
                              `offer_truck_year` ,
                              `offer_truck_serial` ,
                              `offer_truck_weight` ,
                              `offer_truck_extras` ,
                              `offer_truck_desc` ,
                              `offer_truck_internal-desc` ,
                              `offer_truck_depot` ,
                              `offer_truck_sub-depot`,
                              `offer_truck_warranty`,
                              `offer_truck_expected-arrival`
                          )
                          SELECT  NULL,
                          {0},
                          `truck_id`,
                          `truck_saxon-id`,
                          `truck_make`,
                          `truck_function`,
                          `truck_model`,
                          `truck_fuel`,
                          `truck_max-load`,
                          `truck_max-height`,
                          `truck_status`,
                          `truck_type`,
                          `truck_cost`,
                          `truck_rent`,
                          `truck_date`,
                          `truck_reserved`,
                          `truck_default-image`,
                          `truck_powered-wheel`,
                          `truck_steered-wheel`,
                          `truck_engine`,
                          `truck_drivetrain`,
                          `truck_hours-used`,
                          `truck_year`,
                          `truck_serial`,
                          `truck_weight`,
                          `truck_extras`,
                          `truck_desc`,
                          `truck_internal-desc`,
                          `truck_depot`,
                          `truck_sub-depot`,
                          `truck_warranty`,
                          `truck_expected-arrival`
                    FROM `trucks`
                    WHERE truck_id IN ([1])",
    "get_images_by_truck" => "SELECT * FROM `truck_images` WHERE `image_truck-id` IN ([0])",
    "copy_images_to_offer_ROFLMAO" => "INSERT INTO `offer_images` (
                                 `offer_id`,
                                 `offer_image_unique_id`,
                                 `offer_image_truck-id`,
                                 `offer_image_id`,
                                 `offer_image_filename`)
                               SELECT {0},
                                 `image_unique-id`,
                                 `image_truck-id`,
                                 `image_id`,
                                 `image_filename`
                               FROM `truck_images`
                               WHERE `image_truck-id` IN ([1]) AND `image_unique-id` IN ([2])",
    "copy_images_to_offer" => "INSERT INTO `offer_images` (
                                 `offer_id`,
                                 `offer_image_unique_id`,
                                 `offer_image_truck-id`,
                                 `offer_image_id`,
                                 `offer_image_filename`,
                                 `offer_image_enabled`)
                               SELECT {0},
  							     `image_unique-id`,
	  						     `image_truck-id`,
								 `image_id`,
								 `image_filename`,
								 (SELECT '1' FROM trucks WHERE (trucks.truck_id IN ([1]) AND trucks.`truck_default-image` = `image_id` AND trucks.truck_id = `image_truck-id`))
								 FROM `truck_images` WHERE `image_truck-id` IN ([1]) AND `image_unique-id` IN ([2])",
    "get_images_to_copy" => "SELECT * FROM `truck_images` WHERE `image_unique-id` IN ([0])",
    "get_offer_copied_images" => "SELECT `offer_image_unique_id` FROM `offer_images` WHERE `offer_id` = [0]",
    "set_copied_images_enabled" => "UPDATE `offer_images` SET `offer_image_enabled` = 1 WHERE `offer_image_main_id` IN ([0])",
    "set_copied_images_disabled" => "UPDATE `offer_images` SET `offer_image_enabled` = 0 WHERE `offer_image_main_id` IN ([0])",
    "get_offer_copied_images_by_truck" => "SELECT * FROM `offer_images` WHERE `offer_id` = {0} AND `offer_image_truck-id` = {1}",
    "get_offer_copied_trucks" => "SELECT `offer_truck_id` FROM `offer_trucks` WHERE `offer_id` = [0]",
    "set_offer_state" => "UPDATE `offer_requests` SET `offer_status` = {0} WHERE `offer_id` = {1}",
    "set_offer_closed_date" => "UPDATE `offer_requests` SET `offer_date-closed` = NOW()",
    "offer_addimage" => "INSERT INTO offer_images (`offer_image_truck-id`, `offer_image_unique_id`, `offer_image_filename`, `offer_id`) VALUES ({0}, -1, {1}, {2})",
    "offer_requests_edit:truck_mod" => "SELECT
         offer_id,
         offer_truck_id,
        `offer_truck_saxon-id`,
        (SELECT value FROM truck_make_[2] WHERE truck_make_[2].ID = offer_trucks.offer_truck_make) AS offer_truck_make,

        offer_truck_model,
        (SELECT value FROM truck_fuel_[2] WHERE truck_fuel_[2].ID = offer_trucks.offer_truck_fuel) AS offer_truck_fuel,
        `offer_truck_max-load`,
        `offer_truck_max-height`,
        (SELECT value FROM truck_status_[2] WHERE truck_status_[2].ID = offer_trucks.offer_truck_status) AS offer_truck_status,
        (SELECT value FROM truck_type_[2] WHERE truck_type_[2].ID = offer_trucks.offer_truck_type) AS offer_truck_type,
        offer_truck_cost,
        offer_truck_date,
        offer_truck_reserved,
        `offer_truck_default-image`,
        CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = offer_trucks.offer_truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = offer_trucks.offer_truck_depot AND truck_location.subdepot = offer_trucks.`offer_truck_sub-depot`)) AS offer_truck_location,
        offer_truck_desc,
        `offer_truck_powered-wheel`,
        `offer_truck_steered-wheel`,
        `offer_truck_engine`,
        `offer_truck_drivetrain`,
        `offer_truck_hours-used`,
        `offer_truck_year`,
        `offer_truck_serial`,
        `offer_truck_weight`,
        `offer_truck_extras`,
        `offer_truck_internal-desc`,
        `offer_truck_warranty`,
        `offer_truck_expected-arrival`,
        `offer_truck_ocomment`,
        `offer_truck_fake-image`,
        `offer_truck_vtsz`
      FROM `offer_trucks` WHERE `offer_id` = {0} AND `offer_truck_id` = {1}",
    "offer_requests_edit:truck_mod_all" => "SELECT * FROM `offer_trucks` WHERE `offer_id` = {0}",
    "offer_requests_edit:update_truck" => "UPDATE `offer_trucks` SET
      `offer_truck_max-height` = {0},
      `offer_truck_cost` = {1},
      `offer_truck_extras` = {2},
      `offer_truck_drivetrain` = {3},
      `offer_truck_hours-used` = {6},
      `offer_truck_warranty` = {7},
      `offer_truck_expected-arrival` = {8},
      `offer_truck_ocomment` = {9},
      `offer_truck_model` = {10},
      `offer_truck_max-load` = {11},
      `offer_truck_status` = {12},
      `offer_truck_powered-wheel` = {13},
      `offer_truck_steered-wheel` = {14},
      `offer_truck_engine` = {15},
      `offer_truck_vtsz` = {16},
      `offer_truck_fake-image` = {17}
      WHERE `offer_trucks`.`offer_id` = [4] AND `offer_truck_id` = [5]",
    "offer_requests_edit:update_truck2" => "UPDATE `offer_trucks` SET
      `offer_truck_max-height` = {0},
      `offer_truck_cost` = {1},
      `offer_truck_extras` = {2},
      `offer_truck_drivetrain` = {3},
      `offer_truck_hours-used` = {6},
      `offer_truck_warranty` = {7},
      `offer_truck_expected-arrival` = {8},
      `offer_truck_ocomment` = {9},
      `offer_truck_model` = {10},
      `offer_truck_max-load` = {11},
      `offer_truck_status` = {12},
      `offer_truck_powered-wheel` = {13},
      `offer_truck_steered-wheel` = {14},
      `offer_truck_engine` = {15},
      `offer_truck_vtsz` = {16},
      `offer_truck_fake-image` = {17},
      `offer_truck_make` = {18},
      `offer_truck_fuel` = {19},
      `offer_truck_type` = {20},
      `offer_truck_year` = {21},
      `offer_truck_serial` = {22},
      `offer_truck_weight` = {23}
      WHERE `offer_trucks`.`offer_id` = [4] AND `offer_truck_id` = [5]",
    "offer_requests_edit:remove_saxon_id" => "UPDATE `offer_trucks` SET
      `offer_truck_saxon-id` = ''
      WHERE `offer_trucks`.`offer_id` = [0] AND `offer_truck_id` = [1]",
    "offer_request:update" => "UPDATE `offer_requests` SET `offer_trucks` = {1}, `offer_changed` = '1', `offer_date-last-edited` = NOW() WHERE `offer_id` = {0}",
    "get_offer_request_trucks:user" => "SELECT offer_trucks FROM `offer_requests` WHERE `offer_user-id`={0}",
    "truckman_type_exists" => "SELECT * FROM `truck_type_[0]` WHERE `ID` = [1]",
    "truckman_add_type" => "INSERT INTO `truck_type_[2]` (`ID`, `value`, `ispart`) VALUES (NULL, {0}, {1});",
    "truckman_add_type_id" => "INSERT INTO `truck_type_[2]` (`ID`, `value`, `ispart`) VALUES ([3], {0}, {1});",
    "truckman_find_type" => "SELECT `ID` as `id` FROM `truck_type_hun` WHERE `value` = {0} AND `ispart` = {1}",
    "truckman_get_type_count" => "SELECT COUNT(*) AS `count` FROM `truck_type_hun` WHERE `value` = {0} AND `ispart` = {1}",
    "truckman_add_make" => "INSERT INTO `truck_make` (`ID`, `value`, `ispart`) VALUES (NULL, {0}, [1]);",
    "truckman_find_make" => "SELECT `ID` as `id` FROM `truck_make_" . $lang . "` WHERE `value` = {0} AND `ispart` = [1]",
    "truckman_get_make_count" => "SELECT COUNT(*) AS `count` FROM `truck_make_" . $lang . "` WHERE `value` = {0} AND `ispart` = [1]",
    "truckman_add_truck" => "INSERT INTO `trucks` (
      `truck_id` ,
      `truck_saxon-id`,
      `truck_make`,
      `truck_model`,
      `truck_fuel`,
      `truck_max-load`,
      `truck_max-height`,
      `truck_status`,
      `truck_type`,
      `truck_cost`,
      `truck_rent`,
      `truck_date`,
      `truck_reserved`,
      `truck_special-offer-active`,
      `truck_special-offer-start`,
      `truck_special-offer-end`,
      `truck_special-offer-price`,
      `truck_default-image`,
      `truck_powered-wheel`,
      `truck_steered-wheel`,
      `truck_engine`,
      `truck_drivetrain`,
      `truck_hours-used`,
      `truck_year`,
      `truck_serial`,
      `truck_weight`,
      `truck_extras`,
      `truck_desc`,
      `truck_internal-desc`,
      `truck_depot`,
      `truck_sub-depot`,
      `truck_state`,
      `truck_warranty`,
      `truck_expected-arrival`,
      `truck_temp`,
      `truck_ispart`,
      `truck_short-comment`,
      `truck_forks`
      )
      VALUES (
      NULL , {0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, '0', NOW(), '0', '0', '2000-01-01', '2000-01-01', '0', '0', {9}, {10}, {11}, {12}, {13}, {14}, {15}, {16}, {17}, {18}, {19}, {20}, {21}, 'H',{22},{23},{24},{25},{26},{27}
      );",
    "truckman_modify_truck_ispart" => "UPDATE `trucks` SET
      `truck_ispart` = {1},
      `truck_date` = NOW()
      WHERE `truck_id` = {0}",
    "truckman_modify_truck_base" => "UPDATE `trucks` SET
      `truck_internal-desc` = {1},
      `truck_date` = NOW()
      WHERE `truck_id` = {0}",
    "truckman_modify_truck" => "UPDATE `trucks` SET
      `truck_make` = {1},
      `truck_model` = {2},
      `truck_fuel` = {3},
      `truck_max-load` = {4},
      `truck_max-height` = {5},
      `truck_status` = {6},

       `truck_full-height` = {7},
       `truck_cabin-height` = {8},
       `truck_length` = {9},
       `truck_width` = {10},
       `truck_lifting-column-height` = {11},

      `truck_type` = {12},
      `truck_cost` = {13},
      `truck_reseller_price` = {14},
      `truck_powered-wheel` = {15},
      `truck_steered-wheel` = {16},
      `truck_engine` = {17},
      `truck_drivetrain` = {18},
      `truck_hours-used` = {19},
      `truck_year` = {20},
      `truck_serial` = {21},
      `truck_weight` = {22},
      `truck_extras` = {23},
      `truck_desc` = {24},
      `truck_internal-desc` = {25},
      `truck_depot` = {26},
      `truck_sub-depot` = {27},
      `truck_warranty` = {28},
      `truck_expected-arrival` = {29},
      `truck_short-comment` = {30},
      `truck_forks` = {31},
       truck_public = {32},
       `truck_function` = {33},
       `truck_ispart` = {34},
      `truck_date` = NOW()
      WHERE `truck_id` = {0}",
    /*
      "truckman_modify_truck" => "UPDATE `trucks` SET
      `truck_make` = {1},
      `truck_model` = {2},
      `truck_fuel` = {3},
      `truck_max-load` = {4},
      `truck_max-height` = {5},
      `truck_status` = {6},
      `truck_type` = {7},
      `truck_cost` = {8},
      `truck_powered-wheel` = {9},
      `truck_steered-wheel` = {10},
      `truck_engine` = {11},
      `truck_drivetrain` = {12},
      `truck_hours-used` = {13},
      `truck_year` = {14},
      `truck_serial` = {15},
      `truck_weight` = {16},
      `truck_extras` = {17},
      `truck_desc` = {18},
      `truck_internal-desc` = {19},
      `truck_depot` = {20},
      `truck_sub-depot` = {21},
      `truck_warranty` = {22},
      `truck_expected-arrival` = {23},
      `truck_short-comment` = {24},
      `truck_forks` = {25},
      truck_public = {26},
      `truck_date` = NOW()
      WHERE `truck_id` = {0}",
     */
    "truckman_add_truck_desc" => "",
    "truckman_set_sold" => "UPDATE `trucks` SET `truck_state` = 'S' WHERE `truck_id` = [0]",
    "truckman_edit:get_list" => "SELECT
      `truck_id`,
      `truck_saxon-id`,
      (SELECT value FROM truck_make_" . $lang . " WHERE truck_make_" . $lang . ".ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_" . $lang . " WHERE truck_functions_" . $lang . ".ID = trucks.truck_function) AS truck_function,
      `truck_model`,
      `truck_date`,
      `truck_state`,
      `truck_reserved`,
      `truck_reserve-start`,
      `truck_reserve-end`,
      `truck_type`,
      `truck_fuel`,
      `truck_depot`,
      `truck_cost`,
      `truck_reseller_price`,
      `truck_special-offer-active`,
      `truck_special-offer-start`,
      `truck_special-offer-end`,
      `truck_special-offer-price`,
      (SELECT COUNT(*) FROM truck_images WHERE truck_images.`image_truck-id` = trucks.`truck_id`) AS truck_imagecount,
      (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = trucks.truck_id AND truck_images.image_id = trucks.`truck_default-image` LIMIT 1) AS `truck_image`,
      truck_public
    FROM trucks WHERE `truck_state` != 'S' AND `truck_state` != 'H' [1] ORDER BY [0] LIMIT 5000",
    "truckman_viewsold:get_list" => "SELECT
      `truck_id`,
      `truck_saxon-id`,
      (SELECT value FROM truck_make_" . $lang . " WHERE truck_make_" . $lang . ".ID = trucks.truck_make) AS truck_make,
          (SELECT value FROM truck_functions_" . $lang . " WHERE truck_functions_" . $lang . ".ID = trucks.truck_function) AS truck_function,
      `truck_model`,
      `truck_date`,
      truck_public
    FROM `trucks`
    WHERE `truck_state` = 'S'
    ORDER BY [0]",
    "get_user_data" => "SELECT
      `users_id`,
      `users_login`,
      `users_pass`,
      `users_realname`,
      `users_email`,
      `users_phone`,
      `users_fax`,
      `users_type`,
      `users_date_registered`,
      `users_company`,
      `users_company_temp`,
      (SELECT company_name FROM companies WHERE companies.company_id = users.users_company) AS company_name,
      (SELECT company_country FROM companies WHERE companies.company_id = users.users_company) AS company_country,
      (SELECT company_city FROM companies WHERE companies.company_id = users.users_company) AS company_city,
      (SELECT company_address FROM companies WHERE companies.company_id = users.users_company) AS company_address,
      (SELECT company_zip FROM companies WHERE companies.company_id = users.users_company) AS company_zip,
      (SELECT company_phone FROM companies WHERE companies.company_id = users.users_company) AS company_phone,
      (SELECT company_fax FROM companies WHERE companies.company_id = users.users_company) AS company_fax,
      (SELECT company_email FROM companies WHERE companies.company_id = users.users_company) AS company_email
      FROM `users` WHERE `users_id` = [0]",
    "get_unassigned_user_data" => "SELECT * FROM `users` WHERE `users_company` = -1 AND `users_type` = 0",
    "get_companies" => "SELECT * FROM `companies` WHERE `company_enabled` = 1 ORDER BY `company_name`",
    "get_companiesSearch" => "SELECT * FROM `companies` WHERE `company_enabled` = 1 AND `company_name` like '[0]%' ORDER BY `company_name`",
    "companies:query_similar" => "SELECT * FROM `companies` WHERE `company_name` LIKE '%[0]%' ORDER BY `company_name` ASC",
    "add_company" => "INSERT INTO `companies` ( `company_id` , `company_name` , `company_country` , `company_city` , `company_address` , `company_zip` , `company_phone` , `company_fax` , `company_email` , `company_enabled` )
                        VALUES (
                        NULL , {0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, '1'
                      )",
    "edit_company" => "UPDATE `companies` SET `company_name` = {1}, `company_address` = {2}, `company_zip`={3}, `company_phone`={4}, `company_fax`={5}, `company_email`={6}, `company_city`={7} WHERE `company_id`= [0] ",
    "get_company_by_id" => "SELECT
        `company_id`,
        `company_name`,
        `company_country`,
        `company_address`,
        `company_zip`,
        `company_city`,
        `company_phone`,
        `company_fax`,
        `company_email`,
        `company_enabled`,
        (SELECT `country_prefix` FROM `countries` WHERE `companies`.`company_country` = `countries`.`country_id`) AS `country_prefix`,
        (SELECT `country_phone-prefix` FROM `countries` WHERE `companies`.`company_country` = `countries`.`country_id`) AS `country_phone-prefix`
    FROM `companies` WHERE `company_id` = [0]",
    "assign_user" => "UPDATE `users` SET `users_company` = [1] WHERE `users_id` = [0]",
    "get_user_by_company" => "SELECT * FROM `users` WHERE `users_company` = [0]",
    "get_user_by_name" => "SELECT * FROM `users` WHERE `users_login` = {0}",
    "add_user" => "INSERT INTO `users` ( `users_id` , `users_login` , `users_pass` , `users_realname` , `users_email` , `users_phone` , `users_fax` , `users_type` , `users_date_registered` , `users_company` , `users_company_temp` )
                    VALUES (
                    NULL , {0}, {1}, {2}, {3}, {4}, {5}, '0', NOW(), '-1', {6})",
    "update_user" => "UPDATE `users` SET `users_pass` = {0}, `users_email` = {1}, `users_phone` = {2}, `users_fax` = {3} WHERE `users_id` = {4}",
    "update_user2" => "UPDATE `users` SET `users_email` = {1}, `users_phone` = {2}, `users_fax` = {3}, `users_realname` = {5} WHERE `users_id` = {4}",
    "update_user3" => "UPDATE `users` SET `users_email` = {1}, `users_phone` = {2}, `users_fax` = {3}, `users_realname` = {5}, `users_role` = {6} WHERE `users_id` = {4}",
    "add_user_company" => "INSERT INTO `users` ( `users_id` , `users_login` , `users_pass` , `users_realname` , `users_email` , `users_phone` , `users_fax` , `users_type` , `users_date_registered` , `users_company` , `users_company_temp` , `users_role` )
                            VALUES (
                            NULL , {0}, {1}, {2}, {3}, {4}, {5}, '0', NOW(), {6}, '', {7})",
    "get_all_users_assigned" => "SELECT * FROM `users` WHERE NOT(`users_company` = -1) AND NOT(`users_type` = 255) AND NOT(`users_type` = 128)  ORDER BY `users_id` DESC",
    "flyer:get_flyers" => "SELECT flyer_id, flyer_title FROM flyers",
    "flyer:get_flyer" => "SELECT * FROM flyers WHERE flyer_id = {0} ORDER BY flyer_id DESC",
    "flyer:save" => "UPDATE flyers SET flyer_title={1}, flyer_data={2} WHERE flyer_id={0}",
    "flyer:delete" => "DELETE FROM flyers WHERE flyer_id={0} LIMIT 1",
    "flyer:save_as" => "INSERT INTO flyers (flyer_title, flyer_data) VALUES ({0}, {1})",
    "flyer:saved_id" => "SELECT LAST_INSERT_ID() as `id`",
    "payments" => "SELECT * FROM `paymode` WHERE `State` = 'A'",
    "deliverymethods" => "SELECT * FROM `deliverymethods` WHERE `State` = 'A'",
    "update_offer_request_comment" => "UPDATE `offer_requests` SET `offer_comment` = {1} WHERE `offer_id` = [0]",

    /*
    "excel_get-types" => "SELECT
      `value`,
      `ID`,
      (SELECT COUNT(*) FROM `trucks` WHERE `trucks`.`truck_type` = `truck_type_[0]`.`ID`) AS `count`
    FROM `truck_type_[0]` ORDER BY `count` DESC",
    */
    "excel_get-types" => "SELECT
      `value`,
      `ID`
    FROM `truck_type_[0]` ORDER BY `value` ",

    /*
    "excel_get-types_2" => "SELECT
      `value`,
      `ID`,
	  `ispart`,
      (SELECT COUNT(*) FROM `trucks` WHERE `trucks`.`truck_type` = `truck_type_[0]`.`ID`) AS `count`
    FROM `truck_type_[0]` WHERE `ispart` = {1} ORDER BY `count` DESC",
    */
    "excel_get-types_2" => "SELECT
      `value`,
      `ID`,
	  `ispart`
    FROM `truck_type_[0]` WHERE `ispart` = {1} ORDER BY `value` ",

    "excel_get-sum" => "SELECT
      `value`,
      `ID`,
	  `ispart`
    FROM `truck_type_[0]` WHERE 1 ORDER BY `value` ",
    
    "excel_get-sum-b" => "SELECT
      `value`,
      `ID`,
	  `ispart`
    FROM `truck_type_[0]` WHERE `ispart` = {1} OR `ispart` = {2} or `ispart` = {3} OR `ispart` = {4} ORDER BY `value` ",
    
    "excel_get-sum-c" => "SELECT
      `value`,
      `ID`,
	  `ispart`
    FROM `truck_type_[0]` WHERE `ispart` = {1} OR `ispart` = {2} or `ispart` = {3} ORDER BY `value` ",
    

		/*
    "excel_get-trucks" => "SELECT
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE truck_public = 1 AND `truck_type` = {1}
    ",
    */
    
      "excel_get-trucks-sum" => "SELECT
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE truck_public = 1 AND `truck_type` = {1} ORDER BY `truck_make`, `truck_fuel`, `truck_max-load`",
  
    
    
    
		/*
    "excel_get-trucks" => "SELECT
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE truck_public = 1 AND `truck_type` = {1}
    ",
    */
    "excel_get-trucks" => "SELECT
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE truck_public = 1 AND `truck_type` = {1} ORDER BY `truck_make`, `truck_fuel`, `truck_max-load`",

    "excel_get-trucks_2" => "SELECT
      `truck_id`,
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_hours-used`,
      `truck_year`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
	  `truck_ispart`,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE `truck_type` = {1} AND `truck_ispart` = {2} AND `truck_state` = 'A' ORDER BY `truck_make`, `truck_fuel`, `truck_max-load`",

    "excel_get-trucks_2date" => "SELECT
      `truck_id`,
      `truck_saxon-id`,
      `truck_date`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_hours-used`,
      `truck_year`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
	  `truck_ispart`,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE `truck_type` = {1} AND `truck_ispart` = {2} AND `truck_state` = 'A' ORDER BY `truck_make`, `truck_fuel`, `truck_max-load`",

    "excel_get-trucks_2pub" => "SELECT
      `truck_id`,
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_hours-used`,
      `truck_year`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
	  `truck_ispart`,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE truck_public = {3} AND `truck_type` = {1} AND `truck_ispart` = {2} AND `truck_state` = 'A' ORDER BY `truck_make`, `truck_fuel`, `truck_max-load`",


    "excel_get-trucks_2_R" => "SELECT
      `truck_id`,
      `truck_saxon-id`,
      (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
      (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
      truck_model,
      (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
      `truck_max-load`,
      `truck_hours-used`,
      `truck_year`,
      `truck_max-height`,
      (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,
      truck_cost,
	  `truck_ispart`,
      `truck_short-comment`,
      CONCAT_WS(' ', (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = 0), (SELECT value FROM truck_location WHERE truck_location.depot = trucks.truck_depot AND truck_location.subdepot = trucks.`truck_sub-depot` AND truck_location.subdepot != '0')) AS truck_location
    FROM `trucks`
    WHERE truck_public = 1 AND `truck_saxon-id` LIKE \"R%\" AND `truck_type` = {1} AND `truck_ispart` = {2} AND `truck_state` = 'A' ORDER BY `truck_make`, `truck_fuel`, `truck_max-load`",
    "admin_edit_make:update" => "UPDATE truck_make SET value = {0} WHERE ID = {1}",
    "admin_edit_make:delete" => "DELETE FROM truck_make WHERE ID = {0} LIMIT 1",
    "admin_edit_type:list" => "SELECT
    `truck_type_hun`.`ID`,
    `truck_type_hun`.`value` AS `hunvalue`,
    `truck_type_hun`.`ispart` AS `ispart`,
    (SELECT `truck_type_eng`.`value` FROM `truck_type_eng` WHERE `truck_type_eng`.`ID` = `truck_type_hun`.`ID`) AS `engvalue`,
    (SELECT `truck_type_ger`.`value` FROM `truck_type_ger` WHERE `truck_type_ger`.`ID` = `truck_type_hun`.`ID`) AS `gervalue`
    FROM `truck_type_hun` WHERE `truck_type_hun`.`ispart` = {0} ORDER BY `truck_type_hun`.`ID`",
    /* Gyartok */
    "admin_edit_make:list" => "SELECT
    `truck_make_hun`.`ID`,
    `truck_make_hun`.`value` AS `hunvalue`,
    (SELECT `truck_make_eng`.`value` FROM `truck_make_eng` WHERE `truck_make_eng`.`ID` = `truck_make_hun`.`ID`) AS `engvalue`,
    (SELECT `truck_make_ger`.`value` FROM `truck_make_ger` WHERE `truck_make_ger`.`ID` = `truck_make_hun`.`ID`) AS `gervalue`
    FROM `truck_make_hun`
    ORDER BY `truck_make_hun`.`value` ASC;",
    "admin_edit_make:update" => "UPDATE truck_make_[0] SET value = {1} WHERE ID = {2}",
    //"admin_edit_make:update_ispart_enable" => "UPDATE truck_make_[0] SET ispart = 0 WHERE `ID` IN ([1])",
    //"admin_edit_make:update_ispart_disable" => "UPDATE truck_make_[0] SET ispart = 1 WHERE `ID` NOT IN ([1])",
    "admin_edit_make:delete" => "DELETE FROM truck_make_[0] WHERE ID = {1} LIMIT 1",
    "admin_edit_make:query" => "SELECT COUNT(*) AS `result` FROM truck_make_[0] WHERE ID = {1}",
    "admin_edit_make:insert" => "INSERT INTO truck_make_[0] SET `ID` = {1}, `value` = {2}",
    "admin_edit_make:insertNoID" => "INSERT INTO truck_make_[0] SET `value` = {1}",
    /* Functions */
    "admin_edit_function:list" => "SELECT
    `truck_functions_hun`.`ID`,
    `truck_functions_hun`.`value` AS `hunvalue`,
    (SELECT `truck_functions_eng`.`value` FROM `truck_functions_eng` WHERE `truck_functions_eng`.`ID` = `truck_functions_hun`.`ID`) AS `engvalue`,
    (SELECT `truck_functions_ger`.`value` FROM `truck_functions_ger` WHERE `truck_functions_ger`.`ID` = `truck_functions_hun`.`ID`) AS `gervalue`
    FROM `truck_functions_hun`
    ORDER BY `truck_functions_hun`.`value` ASC;",
    "admin_edit_function:update" => "UPDATE truck_functions_[0] SET value = {1} WHERE ID = {2}",
    "admin_edit_function:delete" => "DELETE FROM truck_functions_[0] WHERE ID = {1} LIMIT 1",
    "admin_edit_function:query" => "SELECT COUNT(*) AS `result` FROM truck_functions_[0] WHERE ID = {1}",
    "admin_edit_function:insert" => "INSERT INTO truck_functions_[0] SET `ID` = {1}, `value` = {2}",
    "admin_edit_function:insertNoID" => "INSERT INTO truck_functions_[0] SET `value` = {1}",
    /*  */
    "admin_edit_type:update" => "UPDATE truck_type_[0] SET value = {1} WHERE ID = {2}",
    "admin_edit_type:update_ispart_enable" => "UPDATE truck_type_[0] SET ispart = 0 WHERE `ID` IN ([1])",
    "admin_edit_type:update_ispart_disable" => "UPDATE truck_type_[0] SET ispart = 1 WHERE `ID` NOT IN ([1])",
    "admin_edit_type:delete" => "DELETE FROM truck_type_[0] WHERE ID = {1} LIMIT 1",
    "admin_edit_type:query" => "SELECT COUNT(*) AS `result` FROM truck_type_[0] WHERE ID = {1}",
    "admin_edit_type:insert" => "INSERT INTO truck_type_[0] SET `ID` = {1}, `value` = {2}, `ispart` = {3}",
    "admin_edit_type:insertNoID" => "INSERT INTO truck_type_[0] SET `value` = {1}, `ispart` = {2}",
    "admin_edit_maxheight:get_all" => "SELECT * FROM `truck_max_height` ORDER BY max_height_hun ASC, max_height_eng ASC;",
    "admin_edit_maxheight:insert" => "INSERT INTO `truck_max_height` (
`max_height_id` ,
`max_height_hun` ,
`max_height_eng`
)
VALUES (
NULL , {0}, {1}
);
;",
    "admin_edit_maxheight:update" => "UPDATE `truck_max_height` SET `max_height_hun` = {0},`max_height_eng` = {1} WHERE `truck_max_height`.`max_height_id` ={2};",
    "get_truck_by_temp" => "SELECT `truck_id` FROM `trucks` WHERE `truck_temp` = {0}",
    "offer_request:remove_truck_from_table" => "DELETE FROM `offer_trucks` WHERE `offer_id` = {0} AND `offer_truck_id` = {1} LIMIT 1",
    "offer_request:get_all_details" => "SELECT * FROM `offer_requests` WHERE `offer_id` = {0}",
    "offer_request:insert_with_all_details" => "INSERT INTO `offer_requests` ([0]) VALUES ([1])",
    "offer_request:get_all_truck_details" => "SELECT * FROM `offer_trucks` WHERE `offer_id` = {0} AND `offer_truck_id` = {1}",
    "offer_request:insert_truck_with_all_details" => "INSERT INTO `offer_trucks` ([0]) VALUES ([1])",
    "countries:query_list" => "SELECT * FROM countries order by country_name",
    "countries:query_short_list" => "SELECT `country_id`, `country_name` FROM countries",
    "countries:query_country" => "SELECT * FROM countries WHERE `country_id` = {0}",
    "daily_offer:insert" => "INSERT INTO `daily_offers` SET `truckID` = {0}, `DATE` = NOW()",
    "daily_offer:query_list" => "SELECT `date`, (SELECT `truck_saxon-id` FROM `trucks` WHERE `trucks`.`truck_id` = `daily_offers`.`truckID`) AS `truckID` FROM `daily_offers`",
    "daily_offer:query_saxonID_list" => "SELECT `truck_id`, `truck_saxon-id` FROM `trucks` WHERE `truck_state` IN ('A', 'I') AND `truck_ispart` = 0 ORDER BY `truck_saxon-id` ASC",
    "daily_offer:query_current" => "SELECT * FROM `daily_offers` ORDER BY `ID` DESC LIMIT 1",
    "auto_spec_offer:query_list" => "SELECT `truck_id`, `truck_saxon-id` FROM `trucks` WHERE `truck_auto-special-offer` = 1 ORDER BY `truck_saxon-id` ASC",
    "auto_spec_offer:query_last_date" => "SELECT `value` FROM `config` WHERE `name` = 'AutoSpecOffer:LastDate'",
    "auto_spec_offer:update_last_date" => "UPDATE `config` SET `value` = {0} WHERE `name` = 'AutoSpecOffer:LastDate'",
    "auto_spec_offer:query_last_file_name" => "SELECT `value` FROM `config` WHERE `name` = 'AutoSpecOffer:LastFileName'",
    "auto_spec_offer:add_trucks" => "UPDATE `trucks` SET `truck_auto-special-offer` = 1 WHERE `truck_id` IN ([0])",
    "auto_spec_offer:remove_truck" => "UPDATE `trucks` SET `truck_auto-special-offer` = 0 WHERE `truck_id` = {0}",
    "promo:get" => "SELECT `truck_id` FROM `trucks` WHERE `truck_status` IN (1, 2, 11) AND (SELECT COUNT(*) FROM `truck_images` WHERE `truck_images`.`image_truck-id` = `trucks`.`truck_id`) > 0 AND `truck_cost` > 0 AND `truck_state` = 'A'",
    //"featured:get" => "SELECT (SELECT `value` FROM `config` WHERE `name` = 'FeaturedTruck1:ID') AS `ID1`, (SELECT `value` FROM `config` WHERE `name` = 'FeaturedTruck2:ID') AS `ID2`",
    "featured:get" => "SELECT (SELECT `value` FROM `config` WHERE `name` = 'FeaturedTruck1:ID') AS `ID1`, (SELECT `value` FROM `config` WHERE `name` = 'FeaturedTruck2:ID') AS `ID2`, (SELECT `value` FROM `config` WHERE `name` = 'FeaturedTruck3:ID') AS `ID3`, (SELECT `value` FROM `config` WHERE `name` = 'FeaturedTruck4:ID') AS `ID4`",
    "featured:set" => "UPDATE `config` SET `value` = {0} WHERE `name` = 'FeaturedTruck[1]:ID'",
    "flyer_setemail" => "UPDATE `config` SET `value` = {0} WHERE `name` = 'CurrentFlyer'",
    "flyer_getemail" => "SELECT `value` FROM `config` WHERE `name` = 'CurrentFlyer'",
    "truck_getState" => "SELECT truck_state FROM trucks WHERE `truck_id` = {0}",
    "offer_request:get_all_images" => "SELECT * FROM offer_images WHERE `offer_id` = {0}",
    "offer_request:insert_image" => "INSERT INTO offer_images (`offer_id`, `offer_image_unique_id`, `offer_image_truck-id`, `offer_image_id`, `offer_image_filename`, `offer_image_enabled`) VALUES ({0}, {1}, {2}, {3}, {4}, {5})",
    "toplist:get_all" => "
        SELECT t.`truck_saxon-id`, t.`truck_model`,t.`truck_state`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].`ID` = t.`truck_make`) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = t.truck_function) AS truck_function,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = t.truck_id AND truck_images.image_id = t.`truck_default-image` LIMIT 1) AS `truck_default-image`
        FROM trucks t
        LEFT JOIN trucks_toplist top ON ( top.list_number = {1} AND t.`truck_saxon-id` = top.`truck_saxon-id`  )
        WHERE top.`truck_order` IS NULL AND t.`truck_state` LIKE 'A'
        ORDER BY t.`truck_saxon-id` ASC
        ",
    "toplist:get_old" => "
        SELECT t.`truck_saxon-id`, t.`truck_model`,t.`truck_state`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].`ID` = t.`truck_make`) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = t.truck_function) AS truck_function,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = t.truck_id AND truck_images.image_id = t.`truck_default-image` LIMIT 1) AS `truck_default-image`
        FROM trucks t
        JOIN trucks_toplist top ON ( top.list_number = {1} AND t.`truck_saxon-id` = top.`truck_saxon-id`  )

        ORDER BY top.`truck_order` ASC
        ",
    "toplist:get" => "
        SELECT *,
				(SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = t.truck_fuel) AS truck_fuel_name,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].`ID` = t.`truck_make`) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = t.truck_function) AS truck_function,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = t.truck_id AND truck_images.image_id = t.`truck_default-image` LIMIT 1) AS `truck_default-image`
        FROM trucks t
        JOIN trucks_toplist top ON ( top.list_number = {1} AND t.`truck_saxon-id` = top.`truck_saxon-id`  )

        ORDER BY top.`truck_order` ASC
        ",
    "toplist:search_old" => "
        SELECT t.`truck_saxon-id`, t.`truck_model`,t.`truck_state`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].`ID` = t.`truck_make`) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = t.truck_function) AS truck_function,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = t.truck_id AND truck_images.image_id = t.`truck_default-image` LIMIT 1) AS `truck_default-image`
        FROM trucks t
        WHERE t.`truck_state` LIKE 'A' [1]
        ORDER BY t.`truck_saxon-id` ASC LIMIT [2]
        ",
		"toplist:search" => "
        SELECT *,
				(SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = t.truck_fuel) AS truck_fuel_name,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].`ID` = t.`truck_make`) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = t.truck_function) AS truck_function,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = t.truck_id AND truck_images.image_id = t.`truck_default-image` LIMIT 1) AS `truck_default-image`
        FROM trucks t
        WHERE t.`truck_state` LIKE 'A' [1]
        ORDER BY t.`truck_saxon-id` ASC LIMIT [2]
        ",
    "admin_admin:get_all" => 'SELECT * FROM users WHERE users_type = 255 OR users_type=128 ORDER BY users_type DESC, users_login ASC;',
    "admin_admin:get" => 'SELECT * FROM users WHERE users_id = {0} LIMIT 0,1;',
    "admin_admin:update" => 'UPDATE users SET users_login = {1},users_realname={2}, users_email = {3}, users_phone = {4}, users_type = {5}  WHERE users_id = {0};',
    "admin_admin:update_password" => 'UPDATE users SET users_pass = MD5({1}) WHERE users_id = {0};',
    "admin_admin:insert" => 'INSERT INTO users (users_login,users_realname, users_email , users_phone , users_type ) VALUES({1},{2},{3},{4},{5} );',
    "admin_admin:delete" => 'DELETE FROM users WHERE users_id = {0};',
    "admin_pages:get_all" => 'SELECT * FROM pages ORDER BY page_id ASC;',
    "admin_pages:get" => 'SELECT * FROM pages WHERE page_id = {0} ;',
    "admin_pages:update" => 'UPDATE pages SET page_content_hun = {1},page_content_eng={2} WHERE page_id = {0};',
    "pages:get" => 'SELECT page_id, page_content_[0] as content FROM pages WHERE page_url = {1};',
    "truck_set_public" => "UPDATE trucks SET `truck_public` = {0} WHERE `truck_id` = {1}; ",
    "export:trucks" => "SELECT
        trucks.`truck_saxon-id`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
        truck_model,
        (SELECT value FROM truck_type_[0] WHERE truck_type_[0].ID = trucks.truck_type) AS truck_type,
        (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,

        (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
        `truck_max-load`,
        `truck_max-height`,
        `truck_full-height`,
        `truck_cabin-height`,
        `truck_length`,
        `truck_width`,
        `truck_lifting-column-height`,

        `truck_powered-wheel`,
        `truck_steered-wheel`,
        `truck_engine`,
        `truck_drivetrain`,
        `truck_hours-used`,
        `truck_year`,
        `truck_serial`,
        `truck_weight`,
        `truck_forks`,
        `truck_extras`,
        `truck_warranty`,
        `truck_expected-arrival`,
        `truck_cost`,
        `truck_desc`,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = trucks.truck_id AND truck_images.image_id = trucks.`truck_default-image` LIMIT 1) AS `truck_default-image`
      FROM trucks
      JOIN trucks_toplist top ON ( top.list_number = {1} AND top.`truck_saxon-id` = trucks.`truck_saxon-id` )
      WHERE trucks.`truck_state` LIKE 'A'
      ORDER BY top.`truck_order` ASC;",
    "export:parts" => "SELECT
        trucks.`truck_saxon-id`,
        (SELECT value FROM truck_make_[0] WHERE truck_make_[0].ID = trucks.truck_make) AS truck_make,
        (SELECT value FROM truck_functions_[0] WHERE truck_functions_[0].ID = trucks.truck_function) AS truck_function,
        truck_model,
        (SELECT value FROM truck_type_[0] WHERE truck_type_[0].ID = trucks.truck_type) AS truck_type,
        (SELECT value FROM truck_status_[0] WHERE truck_status_[0].ID = trucks.truck_status) AS truck_status,

        (SELECT value FROM truck_fuel_[0] WHERE truck_fuel_[0].ID = trucks.truck_fuel) AS truck_fuel,
        `truck_max-load`,
        `truck_max-height`,
        `truck_full-height`,
        `truck_cabin-height`,
        `truck_length`,
        `truck_width`,

        `truck_powered-wheel`,
        `truck_steered-wheel`,
        `truck_engine`,
        `truck_drivetrain`,
        `truck_hours-used`,
        `truck_year`,
        `truck_serial`,
        `truck_weight`,
        `truck_forks`,
        `truck_extras`,
        `truck_warranty`,
        `truck_expected-arrival`,
        `truck_cost`,
        `truck_desc`,
        (SELECT image_filename FROM truck_images WHERE truck_images.`image_truck-id` = trucks.truck_id AND truck_images.image_id = trucks.`truck_default-image` LIMIT 1) AS `truck_default-image`
      FROM trucks
      JOIN parts_toplist top ON ( top.`truck_saxon-id` = trucks.`truck_saxon-id` )
      WHERE trucks.`truck_state` LIKE 'A'
      ORDER BY top.`truck_order` ASC;"
);
?>